// Anthropic Messages ⇄ Google Gemini `generateContent`. Pure translation and streaming mapping
// for the AI Studio wire; the transport (endpoint, auth, envelope) is separated in transport.ts so
// another Google backend can be added without touching any of this.
//
// Prompt-cache rule (the same one every translated provider follows): the generated body must be a
// byte-stable prefix of the next turn's, so nothing here uses a timestamp or a random value, key
// order is fixed, and replayed thinking is dropped from the history.
//
// Gemini-3 thought signatures are the one piece of state that cannot live in the body alone: a
// functionCall part must carry back the `thoughtSignature` the model attached, so the request path
// reads it from a map keyed by our own tool_use id (see thoughtSignatures.ts). A missing signature
// is answered with the documented validator-bypass sentinel — see `SIGNATURE_SENTINEL`.

import crypto from "node:crypto";
import { clampEffort } from "../../compat.ts";
import { estimateTokens, normalizeSchema, serverToolNames, systemText, toolNameForResponses, type AnthropicBlock, type AnthropicRequest, type AnthropicTool } from "../chatgpt/translate.ts";
import { identityPrefix, instructionsSuffix } from "../../identity.ts";

// ---- Gemini wire -------------------------------------------------------------------

export type GeminiPart = {
  text?: string;
  /** Model-internal reasoning; the answer's own text has no such flag. */
  thought?: boolean;
  /**
   * Opaque reasoning-continuity token Google attaches to a functionCall part. Must be sent back
   * verbatim on the next turn.
   */
  thoughtSignature?: string;
  inlineData?: { mimeType: string; data: string };
  functionCall?: { name: string; args?: Record<string, unknown>; id?: string };
  functionResponse?: { name: string; response: Record<string, unknown>; id?: string };
};

export type GeminiContent = { role: "user" | "model"; parts: GeminiPart[] };

export type FunctionDeclaration = {
  name: string;
  description: string;
  /**
   * Full JSON Schema (mutually exclusive with `parameters`, which is the narrower OpenAPI subset).
   * Claude Code's tool schemas include keys the OpenAPI subset rejects, so the JSON-Schema field is
   * the one that can carry them unchanged (see the schema note in ARCHITECTURE §4d).
   */
  parametersJsonSchema: Record<string, unknown>;
};

export type GeminiTool = { functionDeclarations: FunctionDeclaration[] };
// "VALIDATED" is not part of the AI Studio wire; Cloud Code Assist's Antigravity backend forces it
// for Claude models (transport.ts). The translation itself only ever emits AUTO/ANY/NONE.
export type FunctionCallingConfig = { mode: "AUTO" | "ANY" | "NONE" | "VALIDATED"; allowedFunctionNames?: string[] };
export type GeminiGenerationConfig = {
  maxOutputTokens?: number;
  temperature?: number;
  stopSequences?: string[];
  thinkingConfig?: { thinkingLevel?: string; thinkingBudget?: number };
};

export type GeminiRequest = {
  contents: GeminiContent[];
  systemInstruction?: { parts: { text: string }[] };
  tools?: GeminiTool[];
  toolConfig?: { functionCallingConfig: FunctionCallingConfig };
  generationConfig?: GeminiGenerationConfig;
};

export type GoogleEffortCaps = { effortLevels?: string[] };

export type GoogleTranslateOptions = {
  model: string;
  effort?: string;
  caps?: GoogleEffortCaps;
  /** Prefix the system prompt with what the model is. Default true; see identity.ts. */
  identity?: boolean;
  /** Fixed configured text after the system prompt. */
  instructionsAppend?: string;
  /** Signed thought signatures by Anthropic tool_use id, re-attached to their functionCall parts. */
  thoughtSignatures?: { get(id: string): string | undefined };
  /** Add the validator-bypass sentinel to a functionCall part that has no cached signature. */
  signatureSentinel?: boolean;
};

/**
 * The value Google's own thought-signatures guide documents for a fake signature: it "instructs the
 * API to skip validation for that turn", for exactly our case — functionCall parts "that were not
 * generated by the API and therefore don't have an associated thought signature" (migrating a
 * history in). It is a last resort and costs reasoning continuity, so it is used only where a real
 * signature is unavailable, and never on a Gemini 2.5 turn (which never asked for one).
 *
 * Source: https://cloud.google.com/vertex-ai/generative-ai/docs/thought-signatures (read
 * 2026-10-01: "should be a last resort as it will negatively impact model performance").
 */
export const SIGNATURE_SENTINEL = "skip_thought_signature_validator";

// ---- text helpers ------------------------------------------------------------------

function textOf(content: string | AnthropicBlock[] | undefined): string {
  if (typeof content === "string") return content;
  if (!Array.isArray(content)) return "";
  return content
    .filter((block) => block.type === "text")
    .map((block) => String((block as { text?: unknown }).text ?? ""))
    .filter((text) => text.length > 0)
    .join("\n");
}

type InlineImage = { mimeType: string; data: string };

function inlineImages(content: string | AnthropicBlock[] | undefined): InlineImage[] {
  if (!Array.isArray(content)) return [];
  const out: InlineImage[] = [];
  for (const block of content) {
    if (block.type !== "image") continue;
    const source = (block as { source?: { type?: unknown; media_type?: unknown; data?: unknown; url?: unknown } }).source;
    if (source?.type === "base64" && typeof source.data === "string") {
      out.push({ mimeType: typeof source.media_type === "string" ? source.media_type : "image/png", data: source.data });
    }
  }
  return out;
}

// ---- effort → thinkingConfig -------------------------------------------------------

// Google exposes reasoning depth two different ways depending on the model family:
//
//   - Gemini 3 (`gemini-3-*`, `gemini-3.<n>-*`) takes a *level* on
//     `generationConfig.thinkingConfig.thinkingLevel`. The documented allowed values are
//     `minimal`, `low`, `medium`, `high` (Google Cloud "Get started with Gemini 3" / "Gemini 3
//     Flash": Flash supports minimal…high, Pro supports low/high). The Generative Language
//     Discovery document adds a second spelling (`thinkingLevel: "OFF" | "BASIC" | "DEEP"`,
//     ai.google.dev/api/generate-content), which does not agree with the guide — so this is
//     (assumption)-grade and the lower-case guide spelling is used. Our seven-step ladder is
//     clamped onto those four: `max`/`xhigh`→`high`, `none`→`minimal`.
//   - Gemini 2.5 takes a token *budget* on `generationConfig.thinkingConfig.thinkingBudget`
//     (an integer; `0` disables thinking). The per-generation ranges are (assumption): flash
//     0..24576, pro 128..32768 — the numbers below stay well inside both.
//
// A model that matches neither family gets no thinkingConfig at all: inventing a field for an
// unknown model is the one failure shape worse than sending no reasoning hint.
const GEMINI3_LEVELS = ["minimal", "low", "medium", "high"] as const;

/** The Gemini-3 thinking level our effort maps to, or undefined when the effort is not one we know. */
function gemini3Level(effort: string): string | undefined {
  switch (effort) {
    case "none": return "minimal";
    case "minimal": return "minimal";
    case "low": return "low";
    case "medium": return "medium";
    case "high": return "high";
    // The top of our ladder has no separate step on this wire; clamp to the top the wire has.
    case "xhigh": return "high";
    case "max": return "high";
    case "ultra": return "high";
    default: return undefined;
  }
}

/** A Gemini-2.5 thinking budget for our effort, or undefined when the effort is not one we know. */
function gemini25Budget(effort: string): number | undefined {
  switch (effort) {
    case "none": return 0;
    case "minimal": return 1024;
    case "low": return 1024;
    case "medium": return 8192;
    case "high": return 16384;
    case "xhigh": return 24576;
    case "max": return 24576;
    case "ultra": return 24576;
    default: return undefined;
  }
}

function thinkingFamily(model: string): "gemini3" | "gemini25" | null {
  if (/^gemini-3[-.]/.test(model)) return "gemini3";
  if (/^gemini-2\.5/.test(model)) return "gemini25";
  return null;
}

/**
 * The reasoning effort a request will actually put on the wire, named for the identity line. A
 * provider whose caps declare a ladder clamps to it first, so the model is told the level it sees.
 */
function namedEffort(opts: GoogleTranslateOptions): string | undefined {
  if (!opts.effort) return undefined;
  const levels = opts.caps?.effortLevels;
  return levels && levels.length > 0 ? clampEffort(opts.effort, levels) : opts.effort;
}

function thinkingConfigFor(model: string, effort: string | undefined): GeminiGenerationConfig["thinkingConfig"] | undefined {
  if (!effort) return undefined;
  const family = thinkingFamily(model);
  if (family === "gemini3") {
    const level = gemini3Level(effort);
    return level ? { thinkingLevel: level } : undefined;
  }
  if (family === "gemini25") {
    const budget = gemini25Budget(effort);
    return budget === undefined ? undefined : { thinkingBudget: budget };
  }
  return undefined;
}

// ---- messages → contents -----------------------------------------------------------

/** The system text this provider should see: what it is, the caller's prompt, the configured addendum. */
function systemForGoogle(sys: string, opts: GoogleTranslateOptions): string {
  return [identityPrefix({ model: opts.model, effort: namedEffort(opts), identity: opts.identity }), sys, instructionsSuffix({ model: opts.model, instructionsAppend: opts.instructionsAppend })]
    .filter(Boolean)
    .join("\n\n");
}

type PendingCall = { id: string; wireName: string };

/** Build `contents` from the Anthropic history, repairing the tool_call/tool_result adjacency Gemini needs. */
function toContents(req: AnthropicRequest, opts: GoogleTranslateOptions): GeminiContent[] {
  const contents: GeminiContent[] = [];
  const messages = req.messages;

  for (let i = 0; i < messages.length; i++) {
    const message = messages[i]!;
    const blocks = Array.isArray(message.content) ? message.content : null;

    if (message.role === "assistant") {
      const parts: GeminiPart[] = [];
      const calls: PendingCall[] = [];
      // Gemini signs only the first functionCall of a step, so a parallel call with no signature of
      // its own is normal, not missing. The sentinel is for a turn that has no real signature at all
      // (a restart, another model's history), and then only on its first call, where one belongs:
      // sent on every unsigned call it would skip validation — and cost reasoning — on healthy turns.
      const signedTurn = (blocks ?? []).some((block) => block.type === "tool_use" && opts.thoughtSignatures?.get((block as { id: string }).id) !== undefined);
      let sentinelPlaced = false;
      for (const block of blocks ?? []) {
        if (block.type === "text") {
          const text = String((block as { text?: unknown }).text ?? "");
          if (text) parts.push({ text });
        } else if (block.type === "tool_use") {
          const call = block as { id: string; name: string; input: unknown };
          const wireName = toolNameForResponses(call.name);
          calls.push({ id: call.id, wireName });
          const part: GeminiPart = { functionCall: { name: wireName, args: asArgs(call.input), id: call.id } };
          const signature = opts.thoughtSignatures?.get(call.id);
          if (signature) part.thoughtSignature = signature;
          else if (opts.signatureSentinel && !signedTurn && !sentinelPlaced && thinkingFamily(opts.model) === "gemini3") {
            part.thoughtSignature = SIGNATURE_SENTINEL;
            sentinelPlaced = true;
          }
          parts.push(part);
        }
        // thinking / redacted_thinking / anything else: dropped on purpose (cache stability)
      }
      // A turn Gemini cannot represent (thinking-only, for instance) would serialize as `parts: []`,
      // which Gemini rejects; it is skipped rather than sent empty.
      if (parts.length > 0) contents.push({ role: "model", parts });

      if (calls.length > 0) {
        // Gemini requires every functionCall in a turn to be answered by an adjacent functionResponse
        // batch. Gather the tool_result blocks from the user turn(s) that follow, then skip them.
        const required = new Map(calls.map((call) => [call.id, call]));
        const results = new Map<string, AnthropicBlock>();
        const orphanResults: AnthropicBlock[] = [];
        let j = i + 1;
        while (j < messages.length) {
          const next = messages[j]!;
          const nextContent = next.content;
          if (next.role === "assistant" || !Array.isArray(nextContent)) break;
          const resultBlocks = nextContent.filter((b) => b.type === "tool_result");
          if (resultBlocks.length === 0) break;
          for (const block of resultBlocks) {
            const id = (block as { tool_use_id?: unknown }).tool_use_id;
            if (typeof id === "string" && required.has(id) && !results.has(id)) results.set(id, block);
            else orphanResults.push(block);
          }
          j++;
        }
        const responseParts: GeminiPart[] = [];
        for (const call of calls) responseParts.push(functionResponsePart(call, results.get(call.id)));
        for (const orphan of orphanResults) responseParts.push(...orphanResultParts(orphan));
        contents.push({ role: "user", parts: responseParts });
        i = j - 1;
        continue;
      }
      continue;
    }

    // user
    if (typeof message.content === "string") {
      if (message.content) contents.push({ role: "user", parts: [{ text: message.content }] });
      continue;
    }
    const parts: GeminiPart[] = [];
    for (const block of blocks ?? []) {
      if (block.type === "text") {
        const text = String((block as { text?: unknown }).text ?? "");
        if (text) parts.push({ text });
      } else if (block.type === "image") {
        const image = inlineImages([block])[0];
        // Gemini takes base64 bytes through inlineData; a remote URL carries no bytes we hold, so a
        // short marker stands in rather than inlining the URL as a huge text blob.
        if (image) parts.push({ inlineData: { mimeType: image.mimeType, data: image.data } });
        else parts.push({ text: `[image: ${String((block as { source?: { url?: unknown } }).source?.url ?? "")}]` });
      } else if (block.type === "tool_result") {
        // A result with no adjacent call cannot be a functionResponse; it is sent as user text.
        parts.push(...orphanResultParts(block));
      }
      // thinking etc. dropped
    }
    if (parts.length > 0) contents.push({ role: "user", parts });
  }

  // Gemini rejects a request that opens on a functionCall turn ("function call turn comes
  // immediately after a user turn or after a function response turn", HTTP 400). Compaction can
  // truncate a long history so it opens on an assistant tool call.
  const first = contents[0];
  if (first?.role === "model" && first.parts.some((part) => part.functionCall !== undefined)) {
    contents.unshift({ role: "user", parts: [{ text: "(continue)" }] });
  }
  // Gemini also rejects an assistant-tail history ("Requests ending with a model turn are not
  // supported", HTTP 400). A compaction, an interrupt or a replayed turn can leave one.
  const last = contents[contents.length - 1];
  if (!last || last.role === "model") contents.push({ role: "user", parts: [{ text: "(continue)" }] });
  return contents;
}

/** A tool's input as Gemini's `functionCall.args` wants it: a JSON object, never a string. */
function asArgs(input: unknown): Record<string, unknown> {
  if (input && typeof input === "object" && !Array.isArray(input)) return input as Record<string, unknown>;
  if (typeof input === "string") {
    try {
      const parsed = JSON.parse(input) as unknown;
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) return parsed as Record<string, unknown>;
    } catch { /* fall through to the empty object */ }
  }
  return {};
}

const MISSING_TOOL_RESULT = "[missing tool_result for this tool_use in history]";
const EMPTY_TOOL_OUTPUT = "(empty tool output)";
const EMPTY_TEXT = "(empty)";

function functionResponsePart(call: PendingCall, result: AnthropicBlock | undefined): GeminiPart {
  if (!result) {
    // Repair the boundary without inventing success: say a result is missing rather than claiming one.
    return { functionResponse: { name: call.wireName, response: { result: MISSING_TOOL_RESULT }, id: call.id } };
  }
  const block = result as { content?: string | AnthropicBlock[]; is_error?: boolean };
  let output = textOf(block.content);
  if (block.is_error && !output) output = "Tool execution failed";
  if (!output) output = EMPTY_TOOL_OUTPUT;
  return { functionResponse: { name: call.wireName, response: { result: output }, id: call.id } };
}

function orphanResultParts(block: AnthropicBlock): GeminiPart[] {
  const b = block as { content?: string | AnthropicBlock[]; is_error?: boolean };
  let output = textOf(b.content);
  if (b.is_error && !output) output = "Tool execution failed";
  if (!output) output = EMPTY_TOOL_OUTPUT;
  const parts: GeminiPart[] = [{ text: `[Tool result]\n${output}` }];
  for (const image of inlineImages(b.content)) parts.push({ inlineData: { mimeType: image.mimeType, data: image.data } });
  return parts;
}

// ---- tools -------------------------------------------------------------------------

// Anthropic's server-side tools (`web_search` and friends) are run by Anthropic, not by the model
// holding them. Declaring one to this provider offers a tool that cannot execute: the model calls
// it, nothing answers, and the turn returns empty with no error. The same rule every translated
// provider follows.
function functionTools(req: AnthropicRequest): FunctionDeclaration[] {
  const dropped = serverToolNames(req.tools);
  return (req.tools ?? [])
    .filter((tool) => typeof tool.name === "string" && !dropped.has(tool.name))
    .map((tool) => ({
      name: toolNameForResponses(tool.name),
      description: tool.description ?? "",
      parametersJsonSchema: normalizeSchema(tool.input_schema),
    }));
}

/** Whether a `tool_choice` that named a dropped tool would force the model onto something undeclared. */
function choiceSurvives(req: AnthropicRequest): boolean {
  const choice = req.tool_choice;
  return choice?.type === "tool" && !!choice.name && !serverToolNames(req.tools).has(choice.name);
}

function mapToolChoice(req: AnthropicRequest, tools: FunctionDeclaration[]): GeminiRequest["toolConfig"] | undefined {
  // `mode: "ANY"` with no declarations is a guaranteed 400, so a tool-less request sends no config.
  if (tools.length === 0) return undefined;
  const choice = req.tool_choice;
  if (!choice) return undefined;
  if (choice.type === "auto") return { functionCallingConfig: { mode: "AUTO" } };
  if (choice.type === "any") return { functionCallingConfig: { mode: "ANY" } };
  if (choice.type === "none") return { functionCallingConfig: { mode: "NONE" } };
  return choiceSurvives(req)
    ? { functionCallingConfig: { mode: "ANY", allowedFunctionNames: [toolNameForResponses(choice.name!)] } }
    : undefined;
}

export function toGeminiRequest(req: AnthropicRequest, opts: GoogleTranslateOptions): GeminiRequest {
  const out: GeminiRequest = { contents: toContents(req, opts) };
  const sys = systemForGoogle(systemText(req.system), opts);
  if (sys) out.systemInstruction = { parts: [{ text: sys }] };
  const tools = functionTools(req);
  if (tools.length > 0) {
    out.tools = [{ functionDeclarations: tools }];
    const toolConfig = mapToolChoice(req, tools);
    if (toolConfig) out.toolConfig = toolConfig;
  }

  const generationConfig: GeminiGenerationConfig = {};
  if (typeof req.max_tokens === "number") generationConfig.maxOutputTokens = req.max_tokens;
  if (typeof req.temperature === "number") generationConfig.temperature = req.temperature;
  if (Array.isArray(req.stop_sequences) && req.stop_sequences.every((value) => typeof value === "string")) {
    generationConfig.stopSequences = req.stop_sequences as string[];
  }
  const thinkingConfig = thinkingConfigFor(opts.model, namedEffort(opts));
  if (thinkingConfig) generationConfig.thinkingConfig = thinkingConfig;
  if (Object.keys(generationConfig).length > 0) out.generationConfig = generationConfig;

  return out;
}

export { estimateTokens };

// ---- Gemini stream → Anthropic stream ----------------------------------------------

export type AnthropicUsage = { input_tokens: number; output_tokens: number; cache_read_input_tokens: number; cache_creation_input_tokens: number };
export type AnthropicEvent = { event: string; data: Record<string, unknown> };

type TextOutputBlock = { type: "text"; text: string };
type ThinkingOutputBlock = { type: "thinking"; thinking: string };
type ToolOutputBlock = { type: "tool_use"; id: string; name: string; input: unknown; args: string; index: number };
type OutputBlock = TextOutputBlock | ThinkingOutputBlock | ToolOutputBlock;
type OpenBlock = { kind: "text" | "thinking" | "tool"; index: number; toolIndex?: number };

type GeminiChunk = {
  candidates?: { content?: { parts?: GeminiPart[] }; finishReason?: unknown }[];
  usageMetadata?: { promptTokenCount?: unknown; candidatesTokenCount?: unknown; cachedContentTokenCount?: unknown; thoughtsTokenCount?: unknown };
  error?: { message?: unknown; status?: unknown; code?: unknown };
};

/** Called with each functionCall part's (Signatures) as they arrive, so the adapter can remember them. */
export type SignatureSink = (info: { id: string; name: string; signature: string | undefined }) => void;

/** Maps Gemini `streamGenerateContent` SSE chunks to Anthropic Messages SSE. */
export class GoogleStreamMapper {
  private started = false;
  private finished = false;
  private blockIndex = -1;
  private open: OpenBlock | null = null;
  private sawTool = false;
  private finishReason: string | undefined;
  private sawCompletion = false;
  private toolCounter = 0;
  private readonly toolNames: ReadonlyMap<string, string>;
  private readonly onFunctionCall: SignatureSink | undefined;
  readonly messageId = `msg_${crypto.randomBytes(12).toString("hex")}`;
  readonly content: OutputBlock[] = [];
  usage: AnthropicUsage = { input_tokens: 0, output_tokens: 0, cache_read_input_tokens: 0, cache_creation_input_tokens: 0 };
  stopReason: "end_turn" | "tool_use" | "max_tokens" = "end_turn";
  failure: { type: string; message: string } | undefined;

  readonly model: string;
  private readonly startInput: number;

  constructor(model: string, startInput = 0, toolNames: ReadonlyMap<string, string> = new Map(), onFunctionCall?: SignatureSink) {
    this.model = model;
    this.startInput = startInput;
    this.toolNames = toolNames;
    this.onFunctionCall = onFunctionCall;
  }

  get isFinished(): boolean { return this.finished; }
  /** Whether Gemini said the answer was over (a `finishReason` was seen). */
  get completed(): boolean { return this.sawCompletion; }

  start(): AnthropicEvent[] {
    if (this.started) return [];
    this.started = true;
    return [{ event: "message_start", data: { type: "message_start", message: { id: this.messageId, type: "message", role: "assistant", model: this.model, content: [], stop_reason: null, stop_sequence: null, usage: { input_tokens: this.startInput, output_tokens: 0, cache_read_input_tokens: 0, cache_creation_input_tokens: 0 } } } }];
  }

  private closeBlock(): AnthropicEvent[] {
    if (!this.open) return [];
    const index = this.open.index;
    this.open = null;
    return [{ event: "content_block_stop", data: { type: "content_block_stop", index } }];
  }

  private openBlock(kind: "text" | "thinking" | "tool", contentBlock: Record<string, unknown>, toolIndex?: number): AnthropicEvent[] {
    const out = this.closeBlock();
    const index = ++this.blockIndex;
    this.open = { kind, index, ...(toolIndex === undefined ? {} : { toolIndex }) };
    out.push({ event: "content_block_start", data: { type: "content_block_start", index, content_block: contentBlock } });
    return out;
  }

  private setUsage(value: GeminiChunk["usageMetadata"]): void {
    if (!value || typeof value !== "object") return;
    const num = (v: unknown): number => (typeof v === "number" && Number.isFinite(v) ? Math.max(0, v) : 0);
    const prompt = num(value.promptTokenCount);
    const cached = num(value.cachedContentTokenCount);
    const candidates = num(value.candidatesTokenCount);
    const thoughts = num(value.thoughtsTokenCount);
    this.usage = {
      input_tokens: Math.max(0, prompt - cached),
      output_tokens: candidates + thoughts,
      cache_read_input_tokens: cached,
      cache_creation_input_tokens: 0,
    };
  }

  /** The vendor echoes the name it was given; Claude Code only recognises the original. */
  private restore(name: string): string {
    return this.toolNames.get(name) ?? name;
  }

  private feedParts(parts: readonly GeminiPart[]): AnthropicEvent[] {
    const out: AnthropicEvent[] = [];
    for (const part of parts) {
      if (typeof part.text === "string" && part.text) {
        if (part.thought === true) {
          if (!this.open || this.open.kind !== "thinking") {
            this.content.push({ type: "thinking", thinking: "" });
            out.push(...this.openBlock("thinking", { type: "thinking", thinking: "" }));
          }
          const last = this.content[this.content.length - 1];
          if (last?.type === "thinking") last.thinking += part.text;
          out.push({ event: "content_block_delta", data: { type: "content_block_delta", index: this.open!.index, delta: { type: "thinking_delta", thinking: part.text } } });
        } else {
          if (!this.open || this.open.kind !== "text") {
            this.content.push({ type: "text", text: "" });
            out.push(...this.openBlock("text", { type: "text", text: "" }));
          }
          const last = this.content[this.content.length - 1];
          if (last?.type === "text") last.text += part.text;
          out.push({ event: "content_block_delta", data: { type: "content_block_delta", index: this.open!.index, delta: { type: "text_delta", text: part.text } } });
        }
        continue;
      }
      if (part.functionCall && typeof part.functionCall.name === "string") {
        this.sawTool = true;
        const index = this.toolCounter++;
        const name = this.restore(part.functionCall.name);
        const id = `toolu_${crypto.randomBytes(12).toString("hex")}`;
        const args = typeof part.functionCall.args === "object" && part.functionCall.args !== null ? JSON.stringify(part.functionCall.args) : "{}";
        const tool: ToolOutputBlock = { type: "tool_use", id, name, input: {}, args, index };
        this.content.push(tool);
        // A whole functionCall arrives in one part, so it opens, takes its arguments in a single
        // delta, and closes — there is nothing to stream.
        out.push(...this.openBlock("tool", { type: "tool_use", id, name, input: {} }, index));
        out.push({ event: "content_block_delta", data: { type: "content_block_delta", index: this.open!.index, delta: { type: "input_json_delta", partial_json: args } } });
        out.push(...this.closeBlock());
        // Let the adapter remember the signature against the id it just minted, so the next turn can
        // send it back with the replayed functionCall.
        this.onFunctionCall?.({ id, name, signature: typeof part.thoughtSignature === "string" && part.thoughtSignature ? part.thoughtSignature : undefined });
      }
      // inlineData (image output) is not handled in this stage; it is ignored rather than guessed at.
    }
    // A part's own text may have been empty but a later part non-empty; the caller decides on close.
    return out;
  }

  feed(chunk: GeminiChunk): AnthropicEvent[] {
    if (this.finished) return [];
    const out = [...this.start()];
    if (chunk.error && typeof chunk.error === "object") {
      const message = typeof chunk.error.message === "string" ? chunk.error.message : "upstream error";
      const status = typeof chunk.error.status === "string" ? chunk.error.status : undefined;
      return [...out, ...this.fail(message, status)];
    }
    if (chunk.usageMetadata) this.setUsage(chunk.usageMetadata);
    const candidates = Array.isArray(chunk.candidates) ? chunk.candidates : [];
    for (const candidate of candidates) {
      if (typeof candidate?.finishReason === "string" && candidate.finishReason) {
        this.finishReason = candidate.finishReason;
        this.sawCompletion = true;
      }
      const parts = candidate?.content?.parts;
      if (Array.isArray(parts)) out.push(...this.feedParts(parts));
    }
    return out;
  }

  finish(): AnthropicEvent[] {
    if (this.finished) return [];
    this.finished = true;
    this.stopReason = this.sawTool ? "tool_use" : this.finishReason === "MAX_TOKENS" ? "max_tokens" : "end_turn";
    return [...this.start(), ...this.closeBlock(), { event: "message_delta", data: { type: "message_delta", delta: { stop_reason: this.stopReason, stop_sequence: null }, usage: this.usage } }, { event: "message_stop", data: { type: "message_stop" } }];
  }

  fail(message: string, status?: string): AnthropicEvent[] {
    if (this.finished) return [];
    this.finished = true;
    // `overloaded_error` is the one mid-stream error Claude Code retries on its own; `api_error` is
    // final. Gemini's RESOURCE_EXHAUSTED becomes a rate limit the client backs off from.
    const type = status === "RESOURCE_EXHAUSTED" ? "rate_limit_error" : status === "UNAVAILABLE" || status === "INTERNAL" || status === "DEADLINE_EXCEEDED" ? "overloaded_error" : "api_error";
    this.failure = { type, message };
    return [...this.start(), ...this.closeBlock(), { event: "error", data: { type: "error", error: { type, message } } }];
  }

  message(): Record<string, unknown> {
    const content = this.content.map((block) => {
      if (block.type !== "tool_use") return block;
      let input: unknown = {};
      try { input = block.args ? JSON.parse(block.args) : {}; } catch { /* malformed vendor arguments become an empty tool input */ }
      return { type: "tool_use", id: block.id, name: block.name, input };
    });
    return { id: this.messageId, type: "message", role: "assistant", model: this.model, content, stop_reason: this.stopReason, stop_sequence: null, usage: this.usage };
  }
}

export function formatSse(event: AnthropicEvent): string {
  return `event: ${event.event}\ndata: ${JSON.stringify(event.data)}\n\n`;
}
