// Agent files are derived from config, and only the ones this router wrote may be touched. A
// hand-written `muse.md` is the user's, not ours: it must survive a sync untouched, and a generated
// name that collides with it must yield rather than overwrite.
import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import { DEFAULTS, type Config, type Provider } from "../src/config.ts";
import { agentAliases, agentNameFor, syncAgentFiles, withAgentAliases } from "../src/agents.ts";

function tmp(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), "cr-agents-"));
}

function cfgWith(providers: Record<string, Provider>, over: Partial<Config> = {}): Config {
  return { ...DEFAULTS, providers, routes: {}, direct: [], aliases: {}, ...over };
}

const p = (models: string[]): Provider => ({ type: "anthropic-compatible", url: "http://127.0.0.1:9", models: models.map((id) => ({ id })) });

test("(a) two config models generate two files, a hand file is untouched, manifest records two", () => {
  const dir = tmp();
  const manifest = path.join(dir, "generated-agents.json");
  fs.writeFileSync(path.join(dir, "muse.md"), "---\nname: muse\nmodel: hand-written@high\n---\nbody\n");

  syncAgentFiles(cfgWith({ p: p(["model-a", "model-b"]) }), dir, undefined, { manifestPath: manifest });

  assert.ok(fs.existsSync(path.join(dir, "model-a.md")), "model-a generated");
  assert.ok(fs.existsSync(path.join(dir, "model-b.md")), "model-b generated");
  assert.equal(fs.readFileSync(path.join(dir, "muse.md"), "utf8"), "---\nname: muse\nmodel: hand-written@high\n---\nbody\n", "the hand file is byte-identical");
  const m = JSON.parse(fs.readFileSync(manifest, "utf8")) as { agents: string[] };
  assert.deepEqual([...m.agents].sort(), ["model-a", "model-b"]);
});

test("(a2) a generated file carries the exact body, its own name, and @medium when medium is offered", () => {
  const dir = tmp();
  const provider: Provider = { type: "anthropic-compatible", url: "http://127.0.0.1:9", caps: { effortLevels: ["low", "medium", "high"] }, models: [{ id: "deepseek-v4.1-flash" }] };
  syncAgentFiles(cfgWith({ p: provider }), dir, undefined, { manifestPath: path.join(dir, "m.json") });

  const file = fs.readFileSync(path.join(dir, "deepseek-v4-1-flash.md"), "utf8");
  assert.match(file, /^---\nname: deepseek-v4-1-flash\n/, "dots become dashes");
  assert.match(file, /\nmodel: deepseek-v4\.1-flash@medium\n/, "the model id keeps its dot; effort is medium");
  assert.match(file, /작업 디렉터리\(cwd\)에 어떤 파일도 만들지 않는다/);
  assert.match(file, /Generated by ClaudeRipple from config\.json/);
});

test("(b) unchecking a model removes only its file, and updates the manifest", () => {
  const dir = tmp();
  const manifest = path.join(dir, "generated-agents.json");
  syncAgentFiles(cfgWith({ p: p(["model-a", "model-b"]) }), dir, undefined, { manifestPath: manifest });
  assert.ok(fs.existsSync(path.join(dir, "model-b.md")));

  syncAgentFiles(cfgWith({ p: p(["model-a"]) }), dir, undefined, { manifestPath: manifest });

  assert.ok(fs.existsSync(path.join(dir, "model-a.md")), "still ticked, still there");
  assert.equal(fs.existsSync(path.join(dir, "model-b.md")), false, "unticked, removed");
  assert.deepEqual(JSON.parse(fs.readFileSync(manifest, "utf8")).agents, ["model-a"]);
});

test("(c) a hand file already using the generated name wins; the generated one is skipped", () => {
  const dir = tmp();
  const manifest = path.join(dir, "generated-agents.json");
  const hand = "---\nname: model-a\nmodel: something-else\n---\nhand body\n";
  fs.writeFileSync(path.join(dir, "model-a.md"), hand);

  syncAgentFiles(cfgWith({ p: p(["model-a", "model-b"]) }), dir, undefined, { manifestPath: manifest });

  assert.equal(fs.readFileSync(path.join(dir, "model-a.md"), "utf8"), hand, "the hand file is not overwritten");
  assert.ok(fs.existsSync(path.join(dir, "model-b.md")));
  assert.deepEqual(JSON.parse(fs.readFileSync(manifest, "utf8")).agents, ["model-b"]);
});

test("(d) a model two providers declare generates nothing", () => {
  const dir = tmp();
  const manifest = path.join(dir, "generated-agents.json");
  syncAgentFiles(cfgWith({ a: p(["shared-model"]), b: p(["shared-model"]) }), dir, undefined, { manifestPath: manifest });

  assert.deepEqual(fs.readdirSync(dir).filter((f) => f.endsWith(".md")), [], "no file generated");
  // Nothing was ever owned, so there is nothing to record; an empty manifest is not written.
  const owned = fs.existsSync(manifest) ? (JSON.parse(fs.readFileSync(manifest, "utf8")) as { agents: string[] }).agents : [];
  assert.deepEqual(owned, []);
});

test("(e) agentAliases drops @effort, and an explicit alias wins over the derived one", () => {
  const dir = tmp();
  fs.writeFileSync(path.join(dir, "deepseek.md"), "---\nname: deepseek\nmodel: deepseek-v4-pro@medium\n---\n");
  fs.writeFileSync(path.join(dir, "no-model.md"), "---\nname: no-model\n---\n");

  assert.deepEqual(agentAliases(dir), { deepseek: "deepseek-v4-pro" });

  const cfg = cfgWith({ p: p(["other"]) }, { aliases: { deepseek: "explicit-target" } });
  assert.equal(withAgentAliases(cfg, dir).aliases.deepseek, "explicit-target", "cfg.aliases wins");
  assert.equal(withAgentAliases(cfg, dir).aliases["no-model"], undefined, "a file with no model is not an alias");
});

test("(f) agentFiles:false writes nothing and removes nothing", () => {
  const dir = tmp();
  const manifest = path.join(dir, "generated-agents.json");
  const cfg = cfgWith({ p: p(["model-a"]) }, { cli: { ...DEFAULTS.cli, agentFiles: false } });

  syncAgentFiles(cfg, dir, undefined, { manifestPath: manifest });

  assert.equal(fs.existsSync(path.join(dir, "model-a.md")), false, "nothing generated");
  assert.equal(fs.existsSync(manifest), false, "no manifest written");

  // Even an already-owned file survives when the switch is off: the removal loop is gated too.
  fs.writeFileSync(path.join(dir, "model-a.md"), "keep me");
  fs.writeFileSync(manifest, JSON.stringify({ agents: ["model-a"] }));
  syncAgentFiles(cfg, dir, undefined, { manifestPath: manifest });
  assert.equal(fs.readFileSync(path.join(dir, "model-a.md"), "utf8"), "keep me");
});

test("agentNameFor maps everything outside [a-z0-9-] to a dash", () => {
  assert.equal(agentNameFor("deepseek-v4.1-flash"), "deepseek-v4-1-flash");
  assert.equal(agentNameFor("gpt-5.6/terra"), "gpt-5-6-terra");
  assert.equal(agentNameFor("kimi-k3"), "kimi-k3");
});
