// macOS attributes a launchd background item to the code signer of the executable it runs.
// Running `node` directly makes System Settings say "Node.js Foundation". So the agent runs a
// tiny app bundle named ClaudeRipple instead: an ad-hoc signed launcher script that execs node
// with the router. Login Items and the background-activity notice then show "ClaudeRipple".

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

export const BUNDLE_ID = "com.clauderipple.router";

export function bundlePath(home: string): string {
  return path.join(home, "ClaudeRipple.app");
}

export function launcherPath(home: string): string {
  return path.join(bundlePath(home), "Contents", "MacOS", "ClaudeRipple");
}

export function writeBundle(opts: { home: string; node: string; script: string; version: string }): string {
  const app = bundlePath(opts.home);
  const macos = path.join(app, "Contents", "MacOS");
  fs.mkdirSync(macos, { recursive: true });
  fs.writeFileSync(
    path.join(app, "Contents", "Info.plist"),
    `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>ClaudeRipple</string>
  <key>CFBundleDisplayName</key><string>ClaudeRipple</string>
  <key>CFBundleIdentifier</key><string>${BUNDLE_ID}</string>
  <key>CFBundleVersion</key><string>${opts.version}</string>
  <key>CFBundleShortVersionString</key><string>${opts.version}</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>ClaudeRipple</string>
  <key>LSUIElement</key><true/>
  <key>LSBackgroundOnly</key><true/>
</dict>
</plist>
`,
  );
  const launcher = launcherPath(opts.home);
  fs.writeFileSync(
    launcher,
    `#!/bin/sh
# ClaudeRipple router launcher (generated by \`clauderipple install\`).
export CLAUDERIPPLE_HOME="${opts.home}"
exec "${opts.node}" "${opts.script}"
`,
    { mode: 0o755 },
  );
  try {
    execFileSync("codesign", ["--force", "--sign", "-", "--identifier", BUNDLE_ID, app], { stdio: "ignore" });
  } catch {
    /* ad-hoc signing is best effort; the launcher still runs unsigned */
  }
  return launcher;
}

export function removeBundle(home: string): void {
  fs.rmSync(bundlePath(home), { recursive: true, force: true });
}
