// Windows supervisor: a per-user scheduled task that starts the router at logon and restarts it
// if it dies. The launchd counterpart is launchd.ts; supervisor.ts picks between them.
//
// Measured in a Windows 11 VM (2026-09-14) as a standard, non-elevated user:
//   Register-ScheduledTask with LogonType Interactive + RunLevel Limited → "registered OK", no UAC.
// That is the whole reason this is a scheduled task rather than a Windows service: creating a
// service needs administrator rights, and a personal proxy should not ask for them.
//
// Two things launchd gives us for free need doing by hand here:
//   * KeepAlive → RestartCount/RestartInterval, which only fire on a *non-zero* exit. That still
//     covers a crash and the health self-exit (code 75); a clean exit stays exited, which is what
//     `clauderipple stop` wants anyway.
//   * A graceful restart → there is no SIGTERM on Windows (process.kill terminates outright and
//     would cut the drain), so restart asks the router over POST /api/shutdown and waits.

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

export const TASK_NAME = "ClaudeRippleRouter";

export function taskName(): string {
  return process.env.CLAUDERIPPLE_TASK_NAME ?? TASK_NAME;
}

/** Single-quoted PowerShell literal; the only escape inside one is a doubled quote. */
function ps(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function run(script: string): { ok: boolean; out: string } {
  try {
    const out = execFileSync("powershell.exe", ["-NoProfile", "-NonInteractive", "-Command", script], {
      stdio: ["ignore", "pipe", "pipe"],
      windowsHide: true,
    }).toString();
    return { ok: true, out: out.trim() };
  } catch (e) {
    const err = e as { stdout?: Buffer; stderr?: Buffer };
    return { ok: false, out: `${err.stdout?.toString() ?? ""}${err.stderr?.toString() ?? ""}`.trim() };
  }
}

type TaskDefinition = {
  actionCount?: number;
  execute?: string;
  arguments?: string;
  userId?: string;
  runLevel?: number;
  logonType?: number;
  triggerCount?: number;
  triggerType?: string;
  triggerUserId?: string;
  restartCount?: number;
  restartInterval?: string;
  executionTimeLimit?: string;
  multipleInstances?: number;
  allowStartIfOnBatteries?: boolean;
  dontStopIfGoingOnBatteries?: boolean;
};

export function taskDefinitionMatches(value: unknown, expected: { arguments: string; userId: string }): boolean {
  if (!value || typeof value !== "object") return false;
  const task = value as TaskDefinition;
  return (
    task.actionCount === 1 &&
    task.execute?.toLowerCase() === "powershell.exe" &&
    task.arguments === expected.arguments &&
    task.userId?.toLowerCase() === expected.userId.toLowerCase() &&
    task.runLevel === 0 &&
    task.logonType === 3 &&
    task.triggerCount === 1 &&
    task.triggerType === "MSFT_TaskLogonTrigger" &&
    task.triggerUserId?.toLowerCase() === expected.userId.toLowerCase() &&
    task.restartCount === 99 &&
    task.restartInterval === "PT1M" &&
    task.executionTimeLimit === "PT0S" &&
    task.multipleInstances === 2 &&
    task.allowStartIfOnBatteries === true &&
    task.dontStopIfGoingOnBatteries === true
  );
}

/**
 * The task runs a PowerShell launcher rather than node directly, for three reasons.
 *
 * 1. It pins CLAUDERIPPLE_HOME and any extra environment the installer recorded, which a scheduled
 *    task cannot carry on its own, and keeps output in a log file the way StandardOutPath does.
 * 2. `Start-Process` detaches the router from the console: a task started from one inherits it, and
 *    closing that window sends a Ctrl+C — measured 2026-09-14, the router died with 0xC000013A the
 *    moment the installer's window closed.
 * 3. **It is the KeepAlive.** Task Scheduler's RestartCount/RestartInterval only cover failing to
 *    *start* a task; a process that dies while running just ends the task as complete (measured
 *    2026-09-14: the router was killed, the task went back to Ready with 0xFFFFFFFF, and nothing
 *    restarted it for three minutes). So the launcher supervises the router itself, with launchd's
 *    semantics: a non-zero exit — a crash, or the health self-exit 75 — is relaunched; a clean exit
 *    is not, because that is `stop` or the drain half of `restart`, which starts the task again.
 *    A router that keeps dying immediately backs off instead of spinning.
 */
function writeLauncher(opts: { program: string; args: string[]; home: string; env?: Record<string, string> }): string {
  const launcher = path.join(opts.home, "clauderipple-router.ps1");
  const logDir = path.join(opts.home, "logs");
  fs.mkdirSync(logDir, { recursive: true });
  const env = { CLAUDERIPPLE_HOME: opts.home, ...(opts.env ?? {}) };
  const lines = [
    "# Generated by `clauderipple install`. Supervises the router; see schtasks.ts.",
    ...Object.entries(env).map(([k, v]) => `$env:${k} = ${ps(v)}`),
    `$routerArgs = @(${opts.args.map((a) => ps(a)).join(", ")})`,
    `$out = ${ps(path.join(logDir, "launcher.log"))}`,
    `$err = ${ps(path.join(logDir, "launcher.err.log"))}`,
    `$quickFailures = 0`,
    `while ($true) {`,
    `  $startedAt = Get-Date`,
    `  $p = Start-Process -FilePath ${ps(opts.program)} -ArgumentList $routerArgs -WindowStyle Hidden -PassThru -Wait -RedirectStandardOutput $out -RedirectStandardError $err`,
    `  if ($p.ExitCode -eq 0) { break }`,
    `  if (((Get-Date) - $startedAt).TotalSeconds -lt 10) { $quickFailures++ } else { $quickFailures = 0 }`,
    `  Start-Sleep -Seconds $(if ($quickFailures -ge 5) { 60 } else { 2 })`,
    `}`,
  ];
  fs.writeFileSync(launcher, lines.join("\r\n") + "\r\n");
  return launcher;
}

export function installAgent(opts: { program: string; args?: string[]; home: string; env?: Record<string, string> }): string {
  const launcher = writeLauncher({ program: opts.program, args: opts.args ?? [], home: opts.home, ...(opts.env ? { env: opts.env } : {}) });
  const user = `${os.userInfo().username}`;
  const actionArgs = `-NoProfile -NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass -File "${launcher}"`;
  // Updating the generated launcher does not require re-registering an otherwise correct task.
  // Some Windows installations protect an existing per-user task's security descriptor so that
  // even the same unelevated user gets E_ACCESSDENIED from Register-ScheduledTask -Force. Treat the
  // verified existing definition as success; never silently accept a same-named foreign task.
  const existing = run(
    [
      `$t = Get-ScheduledTask -TaskName ${ps(taskName())} -ErrorAction SilentlyContinue`,
      `if ($null -eq $t) { 'null'; exit 0 }`,
      `$a = @($t.Actions); $p = $t.Principal; $tr = @($t.Triggers); $s = $t.Settings`,
      `[pscustomobject]@{ actionCount = $a.Count; execute = $a[0].Execute; arguments = $a[0].Arguments; userId = $p.UserId; runLevel = [int]$p.RunLevel; logonType = [int]$p.LogonType; triggerCount = $tr.Count; triggerType = $tr[0].CimClass.CimClassName; triggerUserId = $tr[0].UserId; restartCount = $s.RestartCount; restartInterval = [string]$s.RestartInterval; executionTimeLimit = [string]$s.ExecutionTimeLimit; multipleInstances = [int]$s.MultipleInstances; allowStartIfOnBatteries = $s.AllowStartIfOnBatteries; dontStopIfGoingOnBatteries = $s.DontStopIfGoingOnBatteries } | ConvertTo-Json -Compress`,
    ].join("; "),
  );
  let definition: unknown = null;
  if (existing.ok) {
    try {
      definition = JSON.parse(existing.out);
    } catch {
      // A malformed inspection result is not trusted; fall through to registration.
    }
  }
  if (taskDefinitionMatches(definition, { arguments: actionArgs, userId: user })) return launcher;
  const script = [
    `$ErrorActionPreference = 'Stop'`,
    `$a = New-ScheduledTaskAction -Execute ${ps("powershell.exe")} -Argument ${ps(actionArgs)}`,
    `$t = New-ScheduledTaskTrigger -AtLogOn -User ${ps(user)}`,
    // Limited: the router needs no elevation, and asking for it would put a UAC prompt at every logon.
    `$p = New-ScheduledTaskPrincipal -UserId ${ps(user)} -LogonType Interactive -RunLevel Limited`,
    `$s = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -RestartCount 99 -RestartInterval (New-TimeSpan -Minutes 1) -ExecutionTimeLimit ([TimeSpan]::Zero) -MultipleInstances IgnoreNew`,
    `Register-ScheduledTask -TaskName ${ps(taskName())} -Action $a -Trigger $t -Principal $p -Settings $s -Force | Out-Null`,
    `'ok'`,
  ].join("; ");
  const r = run(script);
  if (!r.ok) throw new Error(`Register-ScheduledTask failed: ${r.out}`);
  return launcher;
}

export function removeAgent(): boolean {
  const r = run(`Unregister-ScheduledTask -TaskName ${ps(taskName())} -Confirm:$false -ErrorAction Stop; 'ok'`);
  return r.ok;
}

export function agentState(): "running" | "loaded" | "not-loaded" {
  const r = run(`(Get-ScheduledTask -TaskName ${ps(taskName())} -ErrorAction Stop).State`);
  if (!r.ok) return "not-loaded";
  return /^Running/im.test(r.out) ? "running" : "loaded";
}

/**
 * The scheduled task starts PowerShell, which starts the runtime, so the task's own pid is the
 * launcher's. What callers want is the router, so find the process whose command line names our
 * script. The runtime is `node.exe` for a source checkout and `ClaudeRipple.exe` (Electron as
 * Node) for the packaged app — until 0.1.2 only `node.exe` was looked for, so on every packaged
 * install `restart` found no router, skipped the shutdown, and `Start-ScheduledTask` was ignored
 * by the task already running: "Restart Router" never restarted anything (found 2026-09-16).
 */
export function agentPid(): number | null {
  const r = run(
    // Three layouts run the same router: a checkout (packages\router\src\index.ts), an npm
    // install (dist\router\src\index.js) and the packaged app (the .ts under resources). Matching
    // on "router\src\index." covers all three and still cannot match an unrelated process.
    `(Get-CimInstance Win32_Process -Filter "Name='node.exe' OR Name='ClaudeRipple.exe'" | Where-Object { $_.CommandLine -like '*router\\src\\index.*' } | Select-Object -First 1).ProcessId`,
  );
  const n = Number(r.out.trim());
  return r.ok && Number.isFinite(n) && n > 0 ? n : null;
}

export function startAgent(): "already-running" | "started" | "failed" {
  if (agentPid() !== null) return "already-running";
  const r = run(`Start-ScheduledTask -TaskName ${ps(taskName())} -ErrorAction Stop; 'ok'`);
  return r.ok ? "started" : "failed";
}

export function stopAgent(): boolean {
  // Stop the task so the supervisor does not immediately start it again, then let the router drain.
  run(`Stop-ScheduledTask -TaskName ${ps(taskName())} -ErrorAction SilentlyContinue`);
  return true;
}
