// Windows supervisor: a per-user scheduled task that starts the router at logon and restarts it
// if it dies. The launchd counterpart is launchd.ts; supervisor.ts picks between them.
//
// Measured in a Windows 11 VM (2026-09-14) as a standard, non-elevated user:
//   Register-ScheduledTask with LogonType Interactive + RunLevel Limited → "registered OK", no UAC.
// That is the whole reason this is a scheduled task rather than a Windows service: creating a
// service needs administrator rights, and a personal proxy should not ask for them.
//
// Two things launchd gives us for free need doing by hand here:
//   * KeepAlive → RestartCount/RestartInterval, which only fire on a *non-zero* exit. That still
//     covers a crash and the health self-exit (code 75); a clean exit stays exited, which is what
//     `clauderipple stop` wants anyway.
//   * A graceful restart → there is no SIGTERM on Windows (process.kill terminates outright and
//     would cut the drain), so restart asks the router over POST /api/shutdown and waits.

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

export const TASK_NAME = "ClaudeRippleRouter";

export function taskName(): string {
  return process.env.CLAUDERIPPLE_TASK_NAME ?? TASK_NAME;
}

/** Single-quoted PowerShell literal; the only escape inside one is a doubled quote. */
function ps(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function run(script: string): { ok: boolean; out: string } {
  try {
    const out = execFileSync("powershell.exe", ["-NoProfile", "-NonInteractive", "-Command", script], {
      stdio: ["ignore", "pipe", "pipe"],
      windowsHide: true,
    }).toString();
    return { ok: true, out: out.trim() };
  } catch (e) {
    const err = e as { stdout?: Buffer; stderr?: Buffer };
    return { ok: false, out: `${err.stdout?.toString() ?? ""}${err.stderr?.toString() ?? ""}`.trim() };
  }
}

/**
 * The task runs a small PowerShell launcher rather than node directly: it pins CLAUDERIPPLE_HOME
 * and any extra environment the installer recorded, which a scheduled task cannot carry on its own,
 * and it keeps the router's output in a log file the way launchd's StandardOutPath does.
 *
 * PowerShell with a hidden window, not a .cmd: a task started from a console session inherits that
 * console, and closing the window sends the router a Ctrl+C — measured 2026-09-14, the router died
 * with 0xC000013A the moment the installer's window was closed. Start-Process detaches it.
 */
function writeLauncher(opts: { program: string; args: string[]; home: string; env?: Record<string, string> }): string {
  const launcher = path.join(opts.home, "clauderipple-router.ps1");
  const logDir = path.join(opts.home, "logs");
  fs.mkdirSync(logDir, { recursive: true });
  const env = { CLAUDERIPPLE_HOME: opts.home, ...(opts.env ?? {}) };
  const lines = [
    "# Generated by `clauderipple install`. Starts the router detached from any console.",
    ...Object.entries(env).map(([k, v]) => `$env:${k} = ${ps(v)}`),
    `$routerArgs = @(${opts.args.map((a) => ps(a)).join(", ")})`,
    // -Wait so the task keeps tracking the router: without it the launcher exits immediately, the
    // task counts as finished, and RestartCount (our KeepAlive) never sees a crash. -PassThru +
    // exit propagates the router's code, including the health self-exit 75.
    `$p = Start-Process -FilePath ${ps(opts.program)} -ArgumentList $routerArgs -WindowStyle Hidden -PassThru -Wait \`
  -RedirectStandardOutput ${ps(path.join(logDir, "launcher.log"))} -RedirectStandardError ${ps(path.join(logDir, "launcher.err.log"))}`,
    `exit $p.ExitCode`,
  ];
  fs.writeFileSync(launcher, lines.join("\r\n") + "\r\n");
  return launcher;
}

export function installAgent(opts: { program: string; args?: string[]; home: string; env?: Record<string, string> }): string {
  const launcher = writeLauncher({ program: opts.program, args: opts.args ?? [], home: opts.home, ...(opts.env ? { env: opts.env } : {}) });
  const user = `${os.userInfo().username}`;
  const script = [
    `$ErrorActionPreference = 'Stop'`,
    `$a = New-ScheduledTaskAction -Execute ${ps("powershell.exe")} -Argument ${ps(`-NoProfile -NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass -File "${launcher}"`)}`,
    `$t = New-ScheduledTaskTrigger -AtLogOn -User ${ps(user)}`,
    // Limited: the router needs no elevation, and asking for it would put a UAC prompt at every logon.
    `$p = New-ScheduledTaskPrincipal -UserId ${ps(user)} -LogonType Interactive -RunLevel Limited`,
    `$s = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -RestartCount 99 -RestartInterval (New-TimeSpan -Minutes 1) -ExecutionTimeLimit ([TimeSpan]::Zero) -MultipleInstances IgnoreNew`,
    `Register-ScheduledTask -TaskName ${ps(taskName())} -Action $a -Trigger $t -Principal $p -Settings $s -Force | Out-Null`,
    `'ok'`,
  ].join("; ");
  const r = run(script);
  if (!r.ok) throw new Error(`Register-ScheduledTask failed: ${r.out}`);
  return launcher;
}

export function removeAgent(): boolean {
  const r = run(`Unregister-ScheduledTask -TaskName ${ps(taskName())} -Confirm:$false -ErrorAction Stop; 'ok'`);
  return r.ok;
}

export function agentState(): "running" | "loaded" | "not-loaded" {
  const r = run(`(Get-ScheduledTask -TaskName ${ps(taskName())} -ErrorAction Stop).State`);
  if (!r.ok) return "not-loaded";
  return /^Running/im.test(r.out) ? "running" : "loaded";
}

/**
 * The scheduled task starts cmd.exe, which starts node, so the task's own pid is the launcher's.
 * What callers want is the router, so find the node process whose command line names our script.
 */
export function agentPid(): number | null {
  const r = run(
    `(Get-CimInstance Win32_Process -Filter "Name='node.exe'" | Where-Object { $_.CommandLine -like '*packages\\router\\src\\index.ts*' } | Select-Object -First 1).ProcessId`,
  );
  const n = Number(r.out.trim());
  return r.ok && Number.isFinite(n) && n > 0 ? n : null;
}

export function startAgent(): "already-running" | "started" | "failed" {
  if (agentPid() !== null) return "already-running";
  const r = run(`Start-ScheduledTask -TaskName ${ps(taskName())} -ErrorAction Stop; 'ok'`);
  return r.ok ? "started" : "failed";
}

export function stopAgent(): boolean {
  // Stop the task so the supervisor does not immediately start it again, then let the router drain.
  run(`Stop-ScheduledTask -TaskName ${ps(taskName())} -ErrorAction SilentlyContinue`);
  return true;
}
