// Configuration: one JSON file, hot-reloaded on mtime change.
// Home directory layout (default ~/.clauderipple):
//   config.json   this file
//   ca.pem ca.key leaf.pem leaf.key   generated by the installer
//   logs/router.log (+ rotated .1 .2 ...)

import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import type { CompatibleCaps } from "./compat.ts";

export type ProviderModel = {
  id: string;
  name?: string;
  /** Explicit per-model reasoning-effort support. An empty array disables the provider fallback. */
  effortLevels?: string[];
  /** The model's context window, as the vendor's `/models` reported it (`context_length`). */
  contextWindow?: number;
};

/**
 * One credential in a provider's pool. `id` is what the router's health state is keyed on, so it
 * has to stay put across config edits — renaming one resets its cooldown. Never logged.
 */
export type ProviderCredential = {
  id: string;
  headers: Record<string, string>;
  /** Shown in the dashboard instead of the id. Not a secret, so keep the key out of it. */
  label?: string;
};

export type AnthropicCompatibleProvider = {
  /** An HTTP(S) endpoint that speaks Anthropic Messages (DeepSeek, Kimi, GLM, MiniMax, proxenos, ...). */
  type: "anthropic-compatible";
  /** e.g. "http://127.0.0.1:8787" or "https://api.deepseek.com/anthropic" */
  url: string;
  /** Optional headers to set on forwarded requests (e.g. x-api-key). Never logged. */
  headers?: Record<string, string>;
  /**
   * A header this vendor recognises a conversation by, filled with a value that is stable for one
   * conversation and different between two. Vendors that key their prompt cache on it charge full
   * price to anyone who omits it. Absent, nothing extra is sent.
   */
  sessionHeader?: string;
  /**
   * Further credentials for the same provider, tried when `headers` is rate limited or rejected.
   * Each is a complete header set, so vendors that need more than a key still work. A conversation
   * keeps whichever one it is on while that one is healthy, because moving it moves the prompt
   * cache with it. Absent, the provider has exactly the one credential it always had.
   */
  credentials?: ProviderCredential[];
  /** Catalog preset used to populate this provider, if any. */
  preset?: string;
  /** Optional model entries offered by the GUI as suggestions. */
  models?: ProviderModel[];
  /** Prefix the system prompt with a one-line identity so the model knows what it is. Default true. */
  identity?: boolean;
  /** Fixed text appended to the system prompt. Must stay constant across turns or the prompt cache breaks. */
  instructionsAppend?: string;
  /** Compatibility overrides. Unspecified fields fall back to the preset, then strict defaults. */
  caps?: CompatibleCaps;
};

export type ChatGptProvider = {
  /** Your ChatGPT subscription through the Codex backend; Anthropic Messages translated to OpenAI Responses. */
  type: "chatgpt";
  /** "borrow-codex" reads ~/.codex/auth.json (never refreshed by us); "own" uses `clauderipple login` tokens. Default: own if present, else borrow. */
  auth?: "own" | "borrow-codex" | "auto";
  /** Override the backend origin (default https://chatgpt.com/backend-api). */
  url?: string;
  /** Prefix the system prompt with a one-line identity so the model knows what it is. Default true. */
  identity?: boolean;
  /** Fixed text appended to the system prompt. Must stay constant across turns or the prompt cache breaks. */
  instructionsAppend?: string;
  /** Troubleshooting: true = dump failed upstream exchanges to <home>/debug/; "all" = dump every exchange (last 60). */
  debugDump?: boolean | "all";
  /** Reasoning effort when the request carries none. Default "high". */
  defaultEffort?: string;
  /** Models offered in the GUI (the Codex backend has no listing endpoint). */
  models?: ProviderModel[];
};

export type OpenAiCompatibleProvider = {
  /** An OpenAI-compatible API base, e.g. https://api.x.ai/v1. */
  type: "openai-compatible";
  url: string;
  /** Optional vendor headers, normally authorization: Bearer <key>. Never logged. */
  headers?: Record<string, string>;
  /**
   * A header this vendor uses to recognise a conversation, filled with a value that is stable for
   * one conversation and different between two (`x-opencode-session`, for instance). Vendors that
   * key their prompt cache on it hand a cold cache to anyone who does not send one, which costs
   * several times the tokens. Absent, nothing extra is sent.
   */
  sessionHeader?: string;
  /** OpenAI Chat Completions (default) or stateless Responses endpoint. */
  wire?: "chat" | "responses";
  /** Catalog preset used to populate this provider, if any. */
  preset?: string;
  /** Optional model entries offered by the GUI as suggestions. */
  models?: ProviderModel[];
  /** Prefix the system prompt with a one-line identity so the model knows what it is. Default true. */
  identity?: boolean;
  /** Fixed text appended to the system prompt. Must stay constant across turns or the prompt cache breaks. */
  instructionsAppend?: string;
  /** Reasoning-effort capability exposed by this API/model family. */
  caps?: { effortLevels?: string[]; reasoning?: "effort" | "none" };
};

export type AnthropicProvider = {
  /** Native Anthropic Messages API, available to the OpenAI ingress only. */
  type: "anthropic";
  /** Console API key, or Claude Code's existing OAuth login read without refresh. */
  auth: "api-key" | "claude-code";
  /** Required for api-key unless ANTHROPIC_API_KEY is set. Never logged. */
  apiKey?: string;
  models?: ProviderModel[];
};

export type Provider = AnthropicCompatibleProvider | ChatGptProvider | OpenAiCompatibleProvider | AnthropicProvider;

export type Route = {
  provider: string;
  model: string;
  effort?: string;
  /** Context window for this slot, when the routed model's differs. Falls back to `cli.autoCompactWindow`. */
  contextWindow?: number;
  /**
   * Where the turn goes when this provider cannot answer it — rate limited, rejected, or down.
   * Tried in order, and only for failures another provider could plausibly answer: a bad request
   * is refused everywhere, so it is not retried. Failover ends at the first byte of the answer,
   * because replacing a half-sent stream produces two answers spliced together.
   */
  fallbacks?: { provider: string; model: string; effort?: string }[];
};

export type DirectRule = {
  /** A request whose model starts with this prefix is sent to `provider` with the model unchanged. */
  prefix: string;
  provider: string;
};

export type CliModel = {
  model: string;
  name: string;
  description?: string;
  /**
   * This model's own context window. Routed models do not share one — forcing a single value on a
   * 1M-window model and a 400K one either overflows the smaller or throws away most of the larger.
   * Falls back to `cli.autoCompactWindow`. This is the model's real window, not a compaction
   * threshold: Claude Code applies its own fraction (measured: a 200K window compacted at 151K).
   */
  contextWindow?: number;
};

export type Config = {
  listen: { host: string; port: number; /** OpenAI-compatible ingress port. Defaults to port + 2. */ openaiPort?: number };
  upstream: string;
  providers: Record<string, Provider>;
  /** Picker-slot alias → route. Keys are the model ids the app sends (e.g. "claude-opus-4-8"). */
  routes: Record<string, Route>;
  direct: DirectRule[];
  /** Short names usable in "[[ripple: sol@xhigh]]" markers and "@effort" suffixes. */
  aliases: Record<string, string>;
  effortClamp: Record<string, string>;
  cli: {
    /** Extra entries for the CLI's own /model picker (not the app picker; see docs/ARCHITECTURE.md §3). */
    extraModels: CliModel[];
    /** Fallback context window for routed models that do not declare their own (auto_compact_windows). */
    autoCompactWindow?: number;
    /**
     * Generate `~/.claude/agents/*.md` for the models config declares, so an agent file and the
     * alias a `[[ripple: xxx@effort]]` marker resolves to both come from one place. Only files this
     * router wrote (recorded in `generated-agents.json`) are touched. Default true.
     */
    agentFiles?: boolean;
    /**
     * Which model fills each of Claude Code's own slots, written into `~/.claude/settings.json`
     * env. Claude Code decides these before a request exists, so the router cannot reach them by
     * routing: a search, a session title or a subagent goes wherever the CLI already decided.
     *
     * `smallFast` is the one that matters most. Claude Code runs `WebSearch` as a side request
     * against it, so left at its default a routed session still searches on Claude quota — and a
     * user without a Claude subscription cannot search at all. Pointed at a routed model, the
     * provider does its own search and pays for it (§4).
     *
     * Each is left alone when unset, so nothing here changes behaviour until it is chosen.
     */
    models?: {
      /** ANTHROPIC_MODEL — the session default. */
      main?: string;
      /** ANTHROPIC_SMALL_FAST_MODEL — web search, titles, classifiers. */
      smallFast?: string;
      /** CLAUDE_CODE_SUBAGENT_MODEL — what a subagent runs on unless it names its own. */
      subagent?: string;
    };
  };
  /**
   * Who performs a `WebSearch`. Claude Code sends the search as its own side request to a small
   * model, so by default it costs Claude quota whatever the session is routed to — a routed setup
   * that still cannot search without a Claude subscription. Set this and the named provider's own
   * hosted search answers instead. Absent, nothing is intercepted and the search behaves as before.
   */
  webSearch?: {
    /** A key of `providers`, speaking an OpenAI-compatible Chat Completions API with a web plugin. */
    provider: string;
    /** The model that runs the search. Its hosted search does the work, so a small one is enough. */
    model: string;
    maxResults?: number;
  };
  health: {
    /** Consecutive upstream connect/DNS failures before the process exits for the supervisor to restart it. */
    maxConsecutiveUpstreamFailures: number;
  };
  log: {
    maxBytes: number;
    keep: number;
  };
  /** Local admin API + GUI. Binds 127.0.0.1 only. Defaults to listen.port + 1. */
  admin?: { port: number };
  /**
   * Picker mode: also terminate the app's own claude.ai traffic and add `cli.extraModels`
   * to the model picker. Needs the CA trusted in the login keychain and the app started
   * with our proxy (both done by `clauderipple picker on`).
   */
  picker?: { enabled: boolean; hosts?: string[] };
};

export const PICKER_HOSTS_DEFAULT = ["claude.ai"];

export function terminateHosts(c: Config): string[] {
  const hosts = [c.upstream];
  if (c.picker?.enabled) hosts.push(...(c.picker.hosts ?? PICKER_HOSTS_DEFAULT));
  return hosts;
}

export const DEFAULTS: Config = {
  listen: { host: "127.0.0.1", port: 8790 },
  upstream: "api.anthropic.com",
  providers: {},
  routes: {},
  direct: [],
  aliases: {},
  effortClamp: { ultra: "max" },
  cli: { extraModels: [], agentFiles: true },
  health: { maxConsecutiveUpstreamFailures: 20 },
  log: { maxBytes: 5 * 1024 * 1024, keep: 3 },
};

export function homeDir(): string {
  return process.env.CLAUDERIPPLE_HOME ?? path.join(os.homedir(), ".clauderipple");
}

export function configPath(): string {
  return path.join(homeDir(), "config.json");
}

function merge(base: Config, over: Partial<Config>): Config {
  return {
    ...base,
    ...over,
    listen: { ...base.listen, ...(over.listen ?? {}) },
    cli: { ...base.cli, ...(over.cli ?? {}) },
    health: { ...base.health, ...(over.health ?? {}) },
    log: { ...base.log, ...(over.log ?? {}) },
    effortClamp: { ...base.effortClamp, ...(over.effortClamp ?? {}) },
    ...((over.admin ?? base.admin) ? { admin: over.admin ?? base.admin! } : {}),
    ...(over.picker ? { picker: { ...over.picker } } : {}),
  };
}

/**
 * An HTTP header value is bytes, so anything above U+00FF cannot travel in one. A key pasted with
 * the label beside it — "API 키 sk-…" — fails deep inside the HTTP client with a message about
 * ByteString conversion and a character code, which tells the person nothing about what they did.
 * Returns what to say instead, or null when the value is fine.
 */
export function headerValueProblem(value: string): string | null {
  for (let i = 0; i < value.length; i++) {
    const code = value.charCodeAt(i);
    if (code > 0xff) return `character ${i + 1} is "${value[i]}", which cannot travel in an HTTP header — paste the key on its own, without any label or surrounding text`;
    // A newline would split the header; a stray one usually means a copied line rather than a key.
    if (code === 0x0a || code === 0x0d) return `there is a line break at character ${i + 1} — paste the key on its own, without the line around it`;
  }
  return null;
}

function validModels(models: unknown): boolean {
  return Array.isArray(models) && models.every((model) =>
    model !== null && typeof model === "object" &&
    typeof (model as ProviderModel).id === "string" &&
    ((model as ProviderModel).name === undefined || typeof (model as ProviderModel).name === "string") &&
    ((model as ProviderModel).effortLevels === undefined ||
      (Array.isArray((model as ProviderModel).effortLevels) && (model as ProviderModel).effortLevels!.every((level) => typeof level === "string"))),
  );
}

export function validate(c: Config): string[] {
  const errors: string[] = [];
  for (const [alias, r] of Object.entries(c.routes)) {
    if (!c.providers[r.provider]) errors.push(`route ${alias}: unknown provider "${r.provider}"`);
    if (!r.model) errors.push(`route ${alias}: missing model`);
    // A fallback is only reached when something has already gone wrong, so a broken one is found
    // on the worst possible day. Refuse it at save time instead.
    if (r.fallbacks !== undefined) {
      if (!Array.isArray(r.fallbacks)) errors.push(`route ${alias}: fallbacks must be a list`);
      else r.fallbacks.forEach((f, i) => {
        if (!f || typeof f !== "object") { errors.push(`route ${alias}: fallback ${i} must be an object`); return; }
        if (!c.providers[f.provider]) errors.push(`route ${alias}: fallback ${i} names unknown provider "${f.provider}"`);
        // A native `anthropic` provider answers the OpenAI ingress only; a slot pointing at one
        // makes every request 400 (§5). It is refused as a primary, so refuse it here too.
        else if (c.providers[f.provider]!.type === "anthropic") errors.push(`route ${alias}: fallback ${i} names "${f.provider}", which serves the OpenAI ingress only`);
        if (!f.model || typeof f.model !== "string") errors.push(`route ${alias}: fallback ${i} missing model`);
        if (f.provider === r.provider && f.model === r.model) errors.push(`route ${alias}: fallback ${i} repeats the primary target`);
      });
    }
  }
  for (const d of c.direct) {
    if (!c.providers[d.provider]) errors.push(`direct ${d.prefix}: unknown provider "${d.provider}"`);
  }
  for (const [name, p] of Object.entries(c.providers)) {
    // Carried by every provider that puts together a system prompt, so checked once for all of them.
    const shared = p as { identity?: unknown; instructionsAppend?: unknown };
    if (shared.identity !== undefined && typeof shared.identity !== "boolean") errors.push(`provider ${name}: identity must be true or false`);
    if (shared.instructionsAppend !== undefined && typeof shared.instructionsAppend !== "string") errors.push(`provider ${name}: instructionsAppend must be a string`);
    // Ids key the router's cooldown and quarantine state, so a duplicate would make two credentials
    // share one health record and take each other down.
    const pool = (p as { credentials?: unknown }).credentials;
    if (pool !== undefined) {
      if (!Array.isArray(pool)) errors.push(`provider ${name}: credentials must be a list`);
      else {
        const seen = new Set<string>();
        pool.forEach((entry, i) => {
          const cred = entry as { id?: unknown; headers?: unknown; label?: unknown } | null;
          if (!cred || typeof cred !== "object") { errors.push(`provider ${name}: credential ${i} must be an object`); return; }
          if (typeof cred.id !== "string" || !cred.id) errors.push(`provider ${name}: credential ${i} needs a non-empty id`);
          else if (seen.has(cred.id)) errors.push(`provider ${name}: credential id "${cred.id}" is used twice`);
          else seen.add(cred.id);
          if (!cred.headers || typeof cred.headers !== "object" || Array.isArray(cred.headers) ||
            Object.values(cred.headers as Record<string, unknown>).some((value) => typeof value !== "string")) {
            errors.push(`provider ${name}: credential ${i} headers must be a string record`);
          } else {
            for (const [header, value] of Object.entries(cred.headers as Record<string, string>)) {
              const problem = headerValueProblem(value);
              if (problem) errors.push(`provider ${name}: credential ${i} header "${header}": ${problem}`);
            }
          }
          if (cred.label !== undefined && typeof cred.label !== "string") errors.push(`provider ${name}: credential ${i} label must be a string`);
        });
      }
    }
    if (p.type === "anthropic-compatible") {
      if (!/^https?:\/\//.test(p.url)) errors.push(`provider ${name}: url must start with http:// or https://`);
      if (p.preset !== undefined && typeof p.preset !== "string") errors.push(`provider ${name}: preset must be a string`);
      if (p.models !== undefined && !validModels(p.models)) {
        errors.push(`provider ${name}: models must be entries with string id, optional string name, and optional string[] effortLevels`);
      }
      if (p.caps !== undefined) {
        const caps = p.caps;
        if (!caps || typeof caps !== "object" || Array.isArray(caps) ||
          (caps.effortLevels !== undefined && (!Array.isArray(caps.effortLevels) || caps.effortLevels.some((level) => typeof level !== "string"))) ||
          (caps.thinking !== undefined && caps.thinking !== "enabled" && caps.thinking !== "none") ||
          (caps.betas !== undefined && typeof caps.betas !== "boolean") ||
          (caps.cacheControl !== undefined && typeof caps.cacheControl !== "boolean")) {
          errors.push(`provider ${name}: caps must contain effortLevels?: string[], thinking?: "enabled"|"none", betas?: boolean, cacheControl?: boolean`);
        }
      }
    } else if (p.type === "chatgpt") {
      if (p.models !== undefined && !validModels(p.models)) {
        errors.push(`provider ${name}: models must be entries with string id, optional string name, and optional string[] effortLevels`);
      }
      if (p.url && !/^https?:\/\//.test(p.url)) errors.push(`provider ${name}: url must start with http:// or https://`);
    } else if (p.type === "openai-compatible") {
      if (!/^https?:\/\//.test(p.url)) errors.push(`provider ${name}: url must start with http:// or https://`);
      if (p.wire !== undefined && p.wire !== "chat" && p.wire !== "responses") errors.push(`provider ${name}: wire must be "chat" or "responses"`);
      if (p.preset !== undefined && typeof p.preset !== "string") errors.push(`provider ${name}: preset must be a string`);
      if (p.headers !== undefined && (!p.headers || typeof p.headers !== "object" || Array.isArray(p.headers) || Object.values(p.headers).some((value) => typeof value !== "string"))) {
        errors.push(`provider ${name}: headers must be a string record`);
      }
      if (p.models !== undefined && !validModels(p.models)) {
        errors.push(`provider ${name}: models must be entries with string id, optional string name, and optional string[] effortLevels`);
      }
      if (p.caps !== undefined && (!p.caps || typeof p.caps !== "object" || Array.isArray(p.caps) ||
        (p.caps.effortLevels !== undefined && (!Array.isArray(p.caps.effortLevels) || p.caps.effortLevels.some((level) => typeof level !== "string"))) ||
        (p.caps.reasoning !== undefined && p.caps.reasoning !== "effort" && p.caps.reasoning !== "none"))) {
        errors.push(`provider ${name}: caps must contain effortLevels?: string[], reasoning?: "effort"|"none"`);
      }
    } else if (p.type === "anthropic") {
      if (p.auth !== "api-key" && p.auth !== "claude-code") errors.push(`provider ${name}: auth must be "api-key" or "claude-code"`);
      if (p.apiKey !== undefined && typeof p.apiKey !== "string") errors.push(`provider ${name}: apiKey must be a string`);
      if (p.models !== undefined && !validModels(p.models)) {
        errors.push(`provider ${name}: models must be entries with string id, optional string name, and optional string[] effortLevels`);
      }
    } else {
      errors.push(`provider ${name}: unknown type "${(p as { type?: string }).type}"`);
    }
  }
  if (!(c.listen.port > 0 && c.listen.port < 65536)) errors.push("listen.port out of range");
  if (c.cli.agentFiles !== undefined && typeof c.cli.agentFiles !== "boolean") errors.push("cli.agentFiles must be true or false");
  if (c.listen.openaiPort !== undefined && !(c.listen.openaiPort >= 0 && c.listen.openaiPort < 65536)) errors.push("listen.openaiPort out of range");
  return errors;
}

export class ConfigStore {
  private current: Config = DEFAULTS;
  private mtimeMs = -1;
  private readonly file: string;
  private readonly onChange: ((c: Config, errors: string[]) => void) | undefined;

  constructor(file = configPath(), onChange?: (c: Config, errors: string[]) => void) {
    this.file = file;
    this.onChange = onChange;
    this.reload(true);
  }

  /** Cheap: one stat per call. Called per request. */
  get(): Config {
    this.reload(false);
    return this.current;
  }

  private reload(initial: boolean): void {
    let st: fs.Stats;
    try {
      st = fs.statSync(this.file);
    } catch {
      if (initial) this.onChange?.(this.current, [`no config at ${this.file}; using defaults`]);
      this.mtimeMs = -1;
      return;
    }
    if (st.mtimeMs === this.mtimeMs) return;
    try {
      const parsed = JSON.parse(fs.readFileSync(this.file, "utf8")) as Partial<Config>;
      const next = merge(DEFAULTS, parsed);
      const errors = validate(next);
      if (errors.length === 0 || initial) this.current = next;
      this.mtimeMs = st.mtimeMs;
      this.onChange?.(this.current, errors);
    } catch (e) {
      this.mtimeMs = st.mtimeMs; // do not re-parse a broken file on every request
      this.onChange?.(this.current, [`config parse error: ${(e as Error).message}`]);
    }
  }
}
