// Configuration: one JSON file, hot-reloaded on mtime change.
// Home directory layout (default ~/.clauderipple):
//   config.json   this file
//   ca.pem ca.key leaf.pem leaf.key   generated by the installer
//   logs/router.log (+ rotated .1 .2 ...)

import fs from "node:fs";
import os from "node:os";
import path from "node:path";

export type AnthropicCompatibleProvider = {
  /** An HTTP(S) endpoint that speaks Anthropic Messages (DeepSeek, Kimi, GLM, MiniMax, proxenos, ...). */
  type: "anthropic-compatible";
  /** e.g. "http://127.0.0.1:8787" or "https://api.deepseek.com/anthropic" */
  url: string;
  /** Optional headers to set on forwarded requests (e.g. x-api-key). Never logged. */
  headers?: Record<string, string>;
  /** Optional model ids offered by the GUI as suggestions. */
  models?: string[];
};

export type ChatGptProvider = {
  /** Your ChatGPT subscription through the Codex backend; Anthropic Messages translated to OpenAI Responses. */
  type: "chatgpt";
  /** "borrow-codex" reads ~/.codex/auth.json (never refreshed by us); "own" uses `clauderipple login` tokens. Default: own if present, else borrow. */
  auth?: "own" | "borrow-codex" | "auto";
  /** Override the backend origin (default https://chatgpt.com/backend-api). */
  url?: string;
  /** Prefix the system prompt with a one-line identity so the model knows what it is. Default true. */
  identity?: boolean;
  /** Fixed text appended to the system prompt. Must stay constant across turns or the prompt cache breaks. */
  instructionsAppend?: string;
  /** Reasoning effort when the request carries none. Default "high". */
  defaultEffort?: string;
  models?: string[];
};

export type Provider = AnthropicCompatibleProvider | ChatGptProvider;

export type Route = {
  provider: string;
  model: string;
  effort?: string;
};

export type DirectRule = {
  /** A request whose model starts with this prefix is sent to `provider` with the model unchanged. */
  prefix: string;
  provider: string;
};

export type CliModel = {
  model: string;
  name: string;
  description?: string;
};

export type Config = {
  listen: { host: string; port: number };
  upstream: string;
  providers: Record<string, Provider>;
  /** Picker-slot alias → route. Keys are the model ids the app sends (e.g. "claude-opus-4-8"). */
  routes: Record<string, Route>;
  direct: DirectRule[];
  /** Short names usable in "[[ripple: sol@xhigh]]" markers and "@effort" suffixes. */
  aliases: Record<string, string>;
  effortClamp: Record<string, string>;
  cli: {
    /** Extra entries for the CLI's own /model picker (not the app picker; see docs/ARCHITECTURE.md §3). */
    extraModels: CliModel[];
    /** Context window applied to every routed model in the CLI bootstrap (auto_compact_windows). */
    autoCompactWindow?: number;
  };
  health: {
    /** Consecutive upstream connect/DNS failures before the process exits for the supervisor to restart it. */
    maxConsecutiveUpstreamFailures: number;
  };
  log: {
    maxBytes: number;
    keep: number;
  };
  /** Local admin API + GUI. Binds 127.0.0.1 only. Defaults to listen.port + 1. */
  admin?: { port: number };
  /**
   * Picker mode: also terminate the app's own claude.ai traffic and add `cli.extraModels`
   * to the model picker. Needs the CA trusted in the login keychain and the app started
   * with our proxy (both done by `clauderipple picker on`).
   */
  picker?: { enabled: boolean; hosts?: string[] };
};

export const PICKER_HOSTS_DEFAULT = ["claude.ai"];

export function terminateHosts(c: Config): string[] {
  const hosts = [c.upstream];
  if (c.picker?.enabled) hosts.push(...(c.picker.hosts ?? PICKER_HOSTS_DEFAULT));
  return hosts;
}

export const DEFAULTS: Config = {
  listen: { host: "127.0.0.1", port: 8790 },
  upstream: "api.anthropic.com",
  providers: {},
  routes: {},
  direct: [],
  aliases: {},
  effortClamp: { ultra: "max" },
  cli: { extraModels: [] },
  health: { maxConsecutiveUpstreamFailures: 20 },
  log: { maxBytes: 5 * 1024 * 1024, keep: 3 },
};

export function homeDir(): string {
  return process.env.CLAUDERIPPLE_HOME ?? path.join(os.homedir(), ".clauderipple");
}

export function configPath(): string {
  return path.join(homeDir(), "config.json");
}

function merge(base: Config, over: Partial<Config>): Config {
  return {
    ...base,
    ...over,
    listen: { ...base.listen, ...(over.listen ?? {}) },
    cli: { ...base.cli, ...(over.cli ?? {}) },
    health: { ...base.health, ...(over.health ?? {}) },
    log: { ...base.log, ...(over.log ?? {}) },
    effortClamp: { ...base.effortClamp, ...(over.effortClamp ?? {}) },
    ...((over.admin ?? base.admin) ? { admin: over.admin ?? base.admin! } : {}),
    ...(over.picker ? { picker: { ...over.picker } } : {}),
  };
}

export function validate(c: Config): string[] {
  const errors: string[] = [];
  for (const [alias, r] of Object.entries(c.routes)) {
    if (!c.providers[r.provider]) errors.push(`route ${alias}: unknown provider "${r.provider}"`);
    if (!r.model) errors.push(`route ${alias}: missing model`);
  }
  for (const d of c.direct) {
    if (!c.providers[d.provider]) errors.push(`direct ${d.prefix}: unknown provider "${d.provider}"`);
  }
  for (const [name, p] of Object.entries(c.providers)) {
    if (p.type === "anthropic-compatible") {
      if (!/^https?:\/\//.test(p.url)) errors.push(`provider ${name}: url must start with http:// or https://`);
    } else if (p.type === "chatgpt") {
      if (p.url && !/^https?:\/\//.test(p.url)) errors.push(`provider ${name}: url must start with http:// or https://`);
    } else {
      errors.push(`provider ${name}: unknown type "${(p as { type?: string }).type}"`);
    }
  }
  if (!(c.listen.port > 0 && c.listen.port < 65536)) errors.push("listen.port out of range");
  return errors;
}

export class ConfigStore {
  private current: Config = DEFAULTS;
  private mtimeMs = -1;
  private readonly file: string;
  private readonly onChange: ((c: Config, errors: string[]) => void) | undefined;

  constructor(file = configPath(), onChange?: (c: Config, errors: string[]) => void) {
    this.file = file;
    this.onChange = onChange;
    this.reload(true);
  }

  /** Cheap: one stat per call. Called per request. */
  get(): Config {
    this.reload(false);
    return this.current;
  }

  private reload(initial: boolean): void {
    let st: fs.Stats;
    try {
      st = fs.statSync(this.file);
    } catch {
      if (initial) this.onChange?.(this.current, [`no config at ${this.file}; using defaults`]);
      this.mtimeMs = -1;
      return;
    }
    if (st.mtimeMs === this.mtimeMs) return;
    try {
      const parsed = JSON.parse(fs.readFileSync(this.file, "utf8")) as Partial<Config>;
      const next = merge(DEFAULTS, parsed);
      const errors = validate(next);
      if (errors.length === 0 || initial) this.current = next;
      this.mtimeMs = st.mtimeMs;
      this.onChange?.(this.current, errors);
    } catch (e) {
      this.mtimeMs = st.mtimeMs; // do not re-parse a broken file on every request
      this.onChange?.(this.current, [`config parse error: ${(e as Error).message}`]);
    }
  }
}
